Doc embedding
machine-intelligence-laboratory/TopicNet pull request #82
Opened 2021-06-24 03:01 UTC by bt2901

2021-06-29 07:34 UTC, Evgeny-Egorov-Projects requested changes

2021-06-29 07:34 UTC, Evgeny-Egorov-Projects commented on topicnet/embeddings/backend/server.py
> +    app.run(port='9001', debug=True)
Полностью аналогичная ситуация как из предыдущего реквеста.

2021-06-29 07:34 UTC, Evgeny-Egorov-Projects commented on topicnet/embeddings/backend/wsgi.py
> +    app.run(port='9000')
точно ли порты должны отличаться? у нас server.py и wsgi.py  работают на разных портах. Работают ли эти порты на эпиктете?

2021-06-29 07:36 UTC, Evgeny-Egorov-Projects commented
Вить по ноутбуку с парафразами не понятно что за метрики и какие лучше - хуже. Нет хорошего читаемого сравнения между моделями. Т.е. открываешь ноутбук там код + циферки, скролишь вниз там какие-то цифры.
В итоге ноутбук не служит своим целям:
1. Показать что эмбеддинги работают
2. Сравнить с другими эмбеддингами

2021-06-29 07:43 UTC, Evgeny-Egorov-Projects commented
Аналогичные замечания по ОБВПТМ правда там добавляется что по ноутбуку загрузка модели не работает и ты грузишь локальную. У нас все так же? Если так это надо срочно чинить.

2021-07-05 20:04 UTC, Evgeny-Egorov-Projects commented
Мерджим?

2021-07-06 06:48 UTC, Evgeny-Egorov-Projects commented on topicnet/embeddings/api.py
> +    req = Request(_SERVER_URL + '/' + model_name)
ок, так проще по путям было работать?

2021-07-06 09:12 UTC, bt2901 commented on topicnet/embeddings/api.py
> +    req = Request(_SERVER_URL + '/' + model_name)
ну, так Владислав настроил перенаправление через nginx, а внутри API это всё равно без разницы.

2021-07-06 13:35 UTC, merged